resource "random_uuid" "staging_archive" {
  count = var.observatory_identity_enabled ? 1 : 0

  lifecycle {
    prevent_destroy = true
  }
}

resource "tls_private_key" "staging_receipt" {
  count     = var.observatory_identity_enabled ? 1 : 0
  algorithm = "ED25519"

  lifecycle {
    prevent_destroy = true
  }
}

data "external" "observatory_source" {
  count   = var.deploy_observatory ? 1 : 0
  program = ["python3", "${path.module}/package-observatory.py"]

  query = {
    source_dir  = abspath("${path.module}/../..")
    revision    = var.observatory_revision
    output_path = abspath("${path.module}/.terraform-generated/observatory-source.tar")
  }
}

locals {
  archive_id = (
    var.observatory_archive_id != "" ?
    var.observatory_archive_id :
    var.observatory_identity_enabled ?
    random_uuid.staging_archive[0].result :
    ""
  )
  source_hash       = var.deploy_observatory ? data.external.observatory_source[0].result.sha256 : ""
  runtime_lock_hash = filesha256("${path.module}/../../observatory/requirements.runtime.lock")
  receipt_key_id = var.observatory_identity_enabled ? format(
    "watershop-%s",
    substr(sha256(tls_private_key.staging_receipt[0].public_key_openssh), 0, 16),
  ) : ""
  runtime_id = var.deploy_observatory ? sha256(join(":", [
    local.source_hash,
    local.runtime_lock_hash,
    var.observatory_revision,
  ])) : ""

  staging_environment_values = var.deploy_observatory ? {
    AWS_ACCESS_KEY_ID         = var.minio_access_key
    AWS_SECRET_ACCESS_KEY     = var.minio_secret_key
    MENDO_ARCHIVE_ROOT        = var.staging_archive_root
    MENDO_OBSERVATORY_BIN     = "${var.observatory_home}/venv/bin"
    MENDO_PYTHON_VERSION      = "3.11"
    MENDO_RELEASE_CHANNEL     = "staging"
    MENDO_RELEASE_WORK_ROOT   = "${var.observatory_home}/releases"
    MENDO_RUN_ROOT            = "${var.observatory_home}/run"
    MENDO_RUNTIME_LOCK_SHA256 = local.runtime_lock_hash
    MENDO_S3_BUCKET           = var.minio_release_bucket
    MENDO_S3_ENDPOINT         = var.minio_endpoint
    MENDO_S3_PREFIX           = "staging"
    MENDO_S3_REGION           = var.minio_region
    MENDO_SOURCE_REVISION     = var.observatory_revision
    MENDO_SOURCE_SHA256       = local.source_hash
    MENDO_STAGING_ARCHIVE_ID  = local.archive_id
  } : {}
  staging_environment = join("\n", concat(
    ["# Generated by terraform/watershop. Do not edit on the host."],
    [
      for name, value in local.staging_environment_values :
      "${name}='${replace(value, "'", "'\"'\"'")}'"
    ],
    [""],
  ))
  receipt_environment_values = var.deploy_observatory ? {
    MENDO_STAGING_RECEIPT_KEY_ID      = local.receipt_key_id
    MENDO_STAGING_RECEIPT_PRIVATE_KEY = base64encode(tls_private_key.staging_receipt[0].private_key_pem)
  } : {}
  receipt_environment = join("\n", concat(
    ["# Generated by terraform/watershop. Do not edit on the host."],
    [
      for name, value in local.receipt_environment_values :
      "${name}='${replace(value, "'", "'\"'\"'")}'"
    ],
    [""],
  ))
}

resource "local_sensitive_file" "staging_environment" {
  count                = var.deploy_observatory ? 1 : 0
  filename             = "${path.module}/.terraform-generated/staging.env"
  content              = local.staging_environment
  file_permission      = "0600"
  directory_permission = "0700"
}

resource "local_sensitive_file" "receipt_environment" {
  count                = var.deploy_observatory ? 1 : 0
  filename             = "${path.module}/.terraform-generated/receipt.env"
  content              = local.receipt_environment
  file_permission      = "0600"
  directory_permission = "0700"
}

resource "null_resource" "observatory" {
  count = var.deploy_observatory ? 1 : 0

  lifecycle {
    precondition {
      condition     = can(regex("^[0-9a-f]{40}$", var.observatory_revision))
      error_message = "observatory_revision must be a complete lowercase Git SHA."
    }
    precondition {
      condition     = var.observatory_identity_enabled
      error_message = "observatory_identity_enabled must remain true while deploying Observatory."
    }
    precondition {
      condition     = fileexists(pathexpand(var.watershop_ssh_private_key_path))
      error_message = "watershop_ssh_private_key_path must name a readable local key."
    }
    precondition {
      condition     = var.watershop_host_key != ""
      error_message = "watershop_host_key must pin the watershop SSH host key."
    }
    precondition {
      condition     = var.minio_access_key != "" && var.minio_secret_key != ""
      error_message = "MinIO credentials are required when deployment is enabled."
    }
  }

  triggers = {
    archive_id        = local.archive_id
    environment_hash  = sha256(local.staging_environment)
    receipt_env_hash  = sha256(local.receipt_environment)
    runtime_lock_hash = local.runtime_lock_hash
    runtime_id        = local.runtime_id
    run_script_hash   = filesha256("${path.module}/../../deploy/watershop/scripts/run-corpus-staging.sh")
    smoke_script_hash = filesha256("${path.module}/../../deploy/watershop/scripts/smoke-corpus-staging.sh")
    source_hash       = local.source_hash
    staging_unit_hash = filesha256("${path.module}/../../deploy/watershop/systemd/mendo-corpus-staging.service")
    smoke_unit_hash   = filesha256("${path.module}/../../deploy/watershop/systemd/mendo-corpus-smoke.service")
  }

  connection {
    type        = "ssh"
    host        = var.watershop_host
    user        = var.watershop_user
    private_key = file(pathexpand(var.watershop_ssh_private_key_path))
    host_key    = var.watershop_host_key
  }

  provisioner "remote-exec" {
    inline = [
      "set -eu",
      "install -d -m 0750 '${var.observatory_home}' '${var.observatory_home}/bin' '${var.observatory_home}/env' '${var.observatory_home}/releases' '${var.observatory_home}/run' '${var.observatory_home}/sources' '${var.observatory_home}/venvs' '${var.observatory_home}/work/deploy' \"$HOME/.config/systemd/user\"",
      "install -d -m 0700 '${var.observatory_home}/work/upload'",
    ]
  }

  provisioner "file" {
    source      = local_sensitive_file.staging_environment[0].filename
    destination = "${var.observatory_home}/work/upload/staging.env"
  }

  provisioner "file" {
    source      = local_sensitive_file.receipt_environment[0].filename
    destination = "${var.observatory_home}/work/upload/receipt.env"
  }

  provisioner "file" {
    source      = data.external.observatory_source[0].result.archive_path
    destination = "${var.observatory_home}/work/upload/observatory-source.tar"
  }

  provisioner "file" {
    source      = "${path.module}/../../deploy/watershop/scripts/run-corpus-staging.sh"
    destination = "${var.observatory_home}/work/upload/run-corpus-staging.sh"
  }

  provisioner "file" {
    source      = "${path.module}/../../deploy/watershop/scripts/smoke-corpus-staging.sh"
    destination = "${var.observatory_home}/work/upload/smoke-corpus-staging.sh"
  }

  provisioner "file" {
    source      = "${path.module}/../../deploy/watershop/systemd/mendo-corpus-staging.service"
    destination = "${var.observatory_home}/work/upload/mendo-corpus-staging.service"
  }

  provisioner "file" {
    source      = "${path.module}/../../deploy/watershop/systemd/mendo-corpus-smoke.service"
    destination = "${var.observatory_home}/work/upload/mendo-corpus-smoke.service"
  }

  provisioner "remote-exec" {
    inline = [
      "set -eu",
      "chmod 0600 '${var.observatory_home}/work/upload/staging.env'",
      "chmod 0600 '${var.observatory_home}/work/upload/receipt.env'",
      "command -v flock >/dev/null 2>&1 || { echo 'required command is unavailable: flock' >&2; exit 2; }",
      "command -v findmnt >/dev/null 2>&1 || { echo 'required command is unavailable: findmnt' >&2; exit 2; }",
      "command -v python3.11 >/dev/null 2>&1 || { echo 'required command is unavailable: python3.11' >&2; exit 2; }",
      "case \"$(findmnt -n -T '/home/shared' -o FSTYPE)\" in nfs|nfs4) ;; *) echo '/home/shared is not on NFS' >&2; exit 2 ;; esac",
      "install -d -m 0750 '${var.staging_archive_root}'",
      "exec 9>'${var.observatory_home}/run/corpus-staging.lock'",
      "flock -n 9 || { echo 'a staging operation is active' >&2; exit 75; }",
      "test \"$(sha256sum '${var.observatory_home}/work/upload/observatory-source.tar' | cut -d ' ' -f 1)\" = '${local.source_hash}'",
      "source_dir='${var.observatory_home}/sources/${local.source_hash}'; source_tmp=\"$source_dir.tmp\"; rm -rf \"$source_tmp\"; mkdir -m 0750 \"$source_tmp\"; tar -xf '${var.observatory_home}/work/upload/observatory-source.tar' -C \"$source_tmp\" --strip-components=1; rm -rf \"$source_dir\"; mv \"$source_tmp\" \"$source_dir\"",
      "venv='${var.observatory_home}/venvs/${local.runtime_id}'; venv_tmp=\"$venv.tmp\"; if [ -e \"$venv\" ]; then test -x \"$venv/bin/mendo-release\"; test \"$(cat \"$venv/mendo-source.sha256\")\" = '${local.source_hash}'; test \"$(cat \"$venv/mendo-runtime-lock.sha256\")\" = '${local.runtime_lock_hash}'; test \"$(cat \"$venv/mendo-source-revision\")\" = '${var.observatory_revision}'; else rm -rf \"$venv_tmp\"; python3.11 -m venv \"$venv_tmp\"; \"$venv_tmp/bin/python\" -m pip install -r \"$source_dir/requirements.runtime.lock\"; \"$venv_tmp/bin/python\" -m pip install \"$source_dir\" --no-deps --no-build-isolation; printf '%s\n' '${local.source_hash}' > \"$venv_tmp/mendo-source.sha256\"; printf '%s\n' '${local.runtime_lock_hash}' > \"$venv_tmp/mendo-runtime-lock.sha256\"; printf '%s\n' '${var.observatory_revision}' > \"$venv_tmp/mendo-source-revision\"; mv \"$venv_tmp\" \"$venv\"; fi",
      "\"$venv/bin/python\" -c 'import mendo_observatory'",
      "set -a; . '${var.observatory_home}/work/upload/staging.env'; set +a",
      "\"$venv/bin/mendo-archive\" init --root '${var.staging_archive_root}' --birthplace '${var.staging_archive_birthplace}' --archive-id '${local.archive_id}'",
      "\"$venv/bin/mendo-release\" ensure-s3-bucket --bucket '${var.minio_release_bucket}' --endpoint-url '${var.minio_endpoint}' --region '${var.minio_region}' --prefix staging",
      "install -m 0755 '${var.observatory_home}/work/upload/run-corpus-staging.sh' '${var.observatory_home}/bin/run-corpus-staging.sh.next'",
      "install -m 0755 '${var.observatory_home}/work/upload/smoke-corpus-staging.sh' '${var.observatory_home}/bin/smoke-corpus-staging.sh.next'",
      "install -m 0644 '${var.observatory_home}/work/upload/mendo-corpus-staging.service' \"$HOME/.config/systemd/user/mendo-corpus-staging.service.next\"",
      "install -m 0644 '${var.observatory_home}/work/upload/mendo-corpus-smoke.service' \"$HOME/.config/systemd/user/mendo-corpus-smoke.service.next\"",
      "mv '${var.observatory_home}/bin/run-corpus-staging.sh.next' '${var.observatory_home}/bin/run-corpus-staging.sh'",
      "mv '${var.observatory_home}/bin/smoke-corpus-staging.sh.next' '${var.observatory_home}/bin/smoke-corpus-staging.sh'",
      "mv \"$HOME/.config/systemd/user/mendo-corpus-staging.service.next\" \"$HOME/.config/systemd/user/mendo-corpus-staging.service\"",
      "mv \"$HOME/.config/systemd/user/mendo-corpus-smoke.service.next\" \"$HOME/.config/systemd/user/mendo-corpus-smoke.service\"",
      "ln -sfn \"$venv\" '${var.observatory_home}/venv.next'",
      "mv -Tf '${var.observatory_home}/venv.next' '${var.observatory_home}/venv'",
      "install -m 0600 '${var.observatory_home}/work/upload/staging.env' '${var.observatory_home}/env/staging.env.next'",
      "install -m 0600 '${var.observatory_home}/work/upload/receipt.env' '${var.observatory_home}/env/receipt.env.next'",
      "mv '${var.observatory_home}/env/staging.env.next' '${var.observatory_home}/env/staging.env'",
      "mv '${var.observatory_home}/env/receipt.env.next' '${var.observatory_home}/env/receipt.env'",
      "rm -f '${var.observatory_home}/work/upload/staging.env' '${var.observatory_home}/work/upload/receipt.env'",
      "export XDG_RUNTIME_DIR=\"/run/user/$(id -u)\"",
      "systemctl --user daemon-reload",
    ]
  }

  depends_on = [
    local_sensitive_file.receipt_environment,
    local_sensitive_file.staging_environment,
  ]
}
