resource "random_password" "workbench_proxy" {
  count   = var.workbench_identity_enabled ? 1 : 0
  length  = 48
  special = false

  lifecycle {
    prevent_destroy = true
  }
}

data "external" "workbench_source" {
  count   = var.deploy_workbench ? 1 : 0
  program = ["python3", "${path.module}/package-workbench.py"]

  query = {
    source_dir  = abspath("${path.module}/../..")
    revision    = var.workbench_revision
    output_path = abspath("${path.module}/.terraform-generated/workbench-source.tar")
  }
}

locals {
  workbench_source_hash = (
    var.deploy_workbench ?
    data.external.workbench_source[0].result.sha256 :
    ""
  )
  workbench_lock_hash = filesha256(
    "${path.module}/../../agents/requirements.runtime.lock"
  )
  workbench_python_version = "3.11"
  workbench_runtime_id = var.deploy_workbench ? sha256(join(":", [
    local.workbench_source_hash,
    local.workbench_lock_hash,
    var.workbench_revision,
    local.workbench_python_version,
  ])) : ""
  workbench_restore_root = var.accepted_workspace_identity_enabled ? (
    "${var.observatory_home}/work/restore-${random_uuid.accepted_workspace_snapshot[0].result}"
  ) : ""
  workbench_environment_values = var.deploy_workbench ? merge({
    AZURE_CLIENT_ID = (
      var.foundry_identity_enabled ?
      azuread_application_registration.foundry_runtime[0].client_id :
      ""
    )
    AZURE_CLIENT_SECRET = (
      var.foundry_identity_enabled ?
      azuread_application_password.foundry_runtime[0].value :
      ""
    )
    AZURE_TENANT_ID                  = var.azure_tenant_id
    ENABLE_SENSITIVE_DATA            = "false"
    FOUNDRY_MODEL                    = var.foundry_model
    FOUNDRY_PROJECT_ENDPOINT         = var.foundry_project_endpoint
    MENDO_CASE_ID                    = "UM_2025-0004"
    MENDO_CHAT_HOST                  = var.workbench_trusted_lan_enabled ? "0.0.0.0" : "127.0.0.1"
    MENDO_FOUNDRY_WEB_SEARCH_ENABLED = "true"
    MENDO_MODEL_PROVIDER             = "foundry"
    MENDO_REPO_ROOT                  = "${var.observatory_home}/app"
    MENDO_RESEARCH_QUEUE_PATH        = "/home/citizen/journalist/research/research-queue.sqlite"
    MENDO_RESEARCH_STAGING_ROOT      = "/home/citizen/journalist/research"
    MENDO_RUN_ROOT                   = "/home/citizen/journalist/research/agent-runs"
    MENDO_WORKBENCH_HOST             = var.workbench_trusted_lan_enabled ? "0.0.0.0" : "127.0.0.1"
    MENDO_WORKBENCH_EXTRA_ARGS = (
      var.workbench_trusted_lan_enabled ?
      "--allow-unauthenticated-private-network" :
      ""
    )
    }, var.workbench_trusted_lan_enabled ? {} : {
    MENDO_WORKBENCH_PROXY_TOKEN = random_password.workbench_proxy[0].result
  }) : {}
  workbench_environment = join("\n", concat(
    ["# Generated by terraform/watershop. Do not edit on the host."],
    [
      for name, value in local.workbench_environment_values :
      "${name}='${replace(value, "'", "'\"'\"'")}'"
    ],
    [""],
  ))
}

resource "local_sensitive_file" "workbench_environment" {
  count                = var.deploy_workbench ? 1 : 0
  filename             = "${path.module}/.terraform-generated/workbench.env"
  content              = local.workbench_environment
  file_permission      = "0600"
  directory_permission = "0700"
}

resource "null_resource" "workbench" {
  count = var.deploy_workbench ? 1 : 0

  lifecycle {
    precondition {
      condition     = can(regex("^[0-9a-f]{40}$", var.workbench_revision))
      error_message = "workbench_revision must be a complete lowercase Git SHA."
    }
    precondition {
      condition     = var.workbench_identity_enabled
      error_message = "workbench_identity_enabled must remain true while deploying Workbench."
    }
    precondition {
      condition     = var.foundry_identity_enabled
      error_message = "foundry_identity_enabled must remain true while deploying Workbench."
    }
    precondition {
      condition     = var.accepted_workspace_identity_enabled
      error_message = "accepted_workspace_identity_enabled must remain true while deploying Workbench."
    }
    precondition {
      condition = (
        var.azure_subscription_id != "" &&
        var.azure_tenant_id != "" &&
        var.foundry_project_resource_id != "" &&
        var.foundry_project_endpoint != "" &&
        var.foundry_model != ""
      )
      error_message = "Azure subscription, tenant, Foundry project, endpoint, and model are required."
    }
    precondition {
      condition     = var.watershop_host_key != ""
      error_message = "watershop_host_key must pin the watershop SSH host key."
    }
  }

  triggers = {
    environment_hash   = sha256(local.workbench_environment)
    hydration_version  = "copy-casebook-data-v2"
    runtime_id         = local.workbench_runtime_id
    chat_service_hash  = filesha256("${path.module}/../../deploy/watershop/systemd/mendo-chat.service")
    service_hash       = filesha256("${path.module}/../../deploy/watershop/systemd/mendo-workbench.service")
    source_hash        = local.workbench_source_hash
    watershop_host_key = data.external.watershop_host_key[0].result.fingerprint
  }

  connection {
    type           = "ssh"
    host           = var.watershop_host
    user           = var.watershop_user
    agent          = true
    agent_identity = pathexpand(var.watershop_ssh_identity_path)
  }

  provisioner "remote-exec" {
    inline = [
      "set -eu",
      "install -d -m 0750 '${var.observatory_home}' '${var.observatory_home}/agent-venvs' '${var.observatory_home}/apps' '${var.observatory_home}/env' '${var.observatory_home}/run' '${var.observatory_home}/work/deploy' \"$HOME/.config/systemd/user\"",
      "install -d -m 0700 '${var.observatory_home}/work/upload'",
    ]
  }

  provisioner "file" {
    source      = local_sensitive_file.workbench_environment[0].filename
    destination = "${var.observatory_home}/work/upload/workbench.env"
  }

  provisioner "file" {
    source      = data.external.workbench_source[0].result.archive_path
    destination = "${var.observatory_home}/work/upload/workbench-source.tar"
  }

  provisioner "file" {
    source      = "${path.module}/../../deploy/watershop/systemd/mendo-chat.service"
    destination = "${var.observatory_home}/work/upload/mendo-chat.service"
  }

  provisioner "file" {
    source      = "${path.module}/../../deploy/watershop/systemd/mendo-workbench.service"
    destination = "${var.observatory_home}/work/upload/mendo-workbench.service"
  }

  provisioner "remote-exec" {
    inline = [
      "set -eu",
      "chmod 0600 '${var.observatory_home}/work/upload/workbench.env'",
      "command -v flock >/dev/null 2>&1 || { echo 'required command is unavailable: flock' >&2; exit 2; }",
      "command -v findmnt >/dev/null 2>&1 || { echo 'required command is unavailable: findmnt' >&2; exit 2; }",
      "command -v python3.11 >/dev/null 2>&1 || { echo 'required command is unavailable: python3.11' >&2; exit 2; }",
      "command -v curl >/dev/null 2>&1 || { echo 'required command is unavailable: curl' >&2; exit 2; }",
      "case \"$(findmnt -n -T '/home/citizen/journalist' -o FSTYPE)\" in nfs|nfs4) ;; *) echo '/home/citizen/journalist is not on NFS' >&2; exit 2 ;; esac",
      "test -w '/home/citizen/journalist' || { echo '/home/citizen/journalist is not writable' >&2; exit 2; }",
      "test -f '${local.workbench_restore_root}/captures/agent-runs/research-queue.sqlite' || { echo 'accepted workspace restore is unavailable' >&2; exit 2; }",
      "test -f '${local.workbench_restore_root}/captures/cases/UM_2025-0004/casebook.sqlite' || { echo 'accepted casebook restore is unavailable' >&2; exit 2; }",
      "install -d -m 0750 '/home/citizen/journalist/research' '/home/citizen/journalist/research/agent-runs'",
      "exec 9>'${var.observatory_home}/run/corpus-staging.lock'",
      "flock -n 9 || { echo 'a staging operation is active' >&2; exit 75; }",
      "queue='/home/citizen/journalist/research/research-queue.sqlite'; if [ ! -e \"$queue\" ]; then cp '${local.workbench_restore_root}/captures/agent-runs/research-queue.sqlite' \"$queue.tmp\"; chmod 0660 \"$queue.tmp\"; mv \"$queue.tmp\" \"$queue\"; fi",
      "python3.11 -c 'import sqlite3,sys; connection=sqlite3.connect(sys.argv[1]); result=connection.execute(\"PRAGMA integrity_check\").fetchone(); connection.close(); assert result == (\"ok\",), result' \"$queue\"",
      "test \"$(sha256sum '${var.observatory_home}/work/upload/workbench-source.tar' | cut -d ' ' -f 1)\" = '${local.workbench_source_hash}'",
      "app='${var.observatory_home}/apps/${local.workbench_source_hash}'; app_tmp=\"$app.tmp\"; if [ ! -d \"$app\" ]; then rm -rf \"$app_tmp\"; mkdir -m 0750 \"$app_tmp\"; tar -xf '${var.observatory_home}/work/upload/workbench-source.tar' -C \"$app_tmp\"; mv \"$app_tmp\" \"$app\"; fi",
      "ln -sfn '${local.workbench_restore_root}/cases' \"$app/cases\"",
      "ln -sfn '${local.workbench_restore_root}/captures' \"$app/captures\"",
      "cp '${local.workbench_restore_root}/web/casebook-data.js' \"$app/web/casebook-data.js.tmp\"; chmod 0644 \"$app/web/casebook-data.js.tmp\"; mv \"$app/web/casebook-data.js.tmp\" \"$app/web/casebook-data.js\"",
      "venv='${var.observatory_home}/agent-venvs/${local.workbench_runtime_id}'; if [ -e \"$venv\" ] && ! { test -x \"$venv/bin/mendo-workbench\" && test \"$(cat \"$venv/mendo-source.sha256\")\" = '${local.workbench_source_hash}' && test \"$(cat \"$venv/mendo-runtime-lock.sha256\")\" = '${local.workbench_lock_hash}' && test \"$(cat \"$venv/mendo-source-revision\")\" = '${var.workbench_revision}' && test \"$(cat \"$venv/mendo-python-version\")\" = '${local.workbench_python_version}' && \"$venv/bin/mendo-workbench\" --help >/dev/null; }; then rm -rf \"$venv\"; fi; if [ ! -e \"$venv\" ]; then python3.11 -m venv \"$venv\"; \"$venv/bin/python\" -m pip install --require-hashes -r \"$app/agents/requirements.runtime.lock\"; \"$venv/bin/python\" -m pip install \"$app/agents\" --no-deps --no-build-isolation; \"$venv/bin/python\" -c \"import sys; assert sys.version_info[:2] == (3, 11), sys.version\"; printf '%s\n' '${local.workbench_source_hash}' > \"$venv/mendo-source.sha256\"; printf '%s\n' '${local.workbench_lock_hash}' > \"$venv/mendo-runtime-lock.sha256\"; printf '%s\n' '${var.workbench_revision}' > \"$venv/mendo-source-revision\"; printf '%s\n' '${local.workbench_python_version}' > \"$venv/mendo-python-version\"; fi",
      "\"$venv/bin/python\" -c 'import mendo_agents.workbench'",
      "install -m 0644 '${var.observatory_home}/work/upload/mendo-chat.service' \"$HOME/.config/systemd/user/mendo-chat.service.next\"",
      "install -m 0644 '${var.observatory_home}/work/upload/mendo-workbench.service' \"$HOME/.config/systemd/user/mendo-workbench.service.next\"",
      "mv \"$HOME/.config/systemd/user/mendo-chat.service.next\" \"$HOME/.config/systemd/user/mendo-chat.service\"",
      "mv \"$HOME/.config/systemd/user/mendo-workbench.service.next\" \"$HOME/.config/systemd/user/mendo-workbench.service\"",
      "ln -sfn \"$app\" '${var.observatory_home}/app.next'",
      "mv -Tf '${var.observatory_home}/app.next' '${var.observatory_home}/app'",
      "ln -sfn \"$venv\" '${var.observatory_home}/agents-venv.next'",
      "mv -Tf '${var.observatory_home}/agents-venv.next' '${var.observatory_home}/agents-venv'",
      "install -m 0600 '${var.observatory_home}/work/upload/workbench.env' '${var.observatory_home}/env/workbench.env.next'",
      "mv '${var.observatory_home}/env/workbench.env.next' '${var.observatory_home}/env/workbench.env'",
      "rm -f '${var.observatory_home}/work/upload/workbench.env'",
      "export XDG_RUNTIME_DIR=\"/run/user/$(id -u)\"",
      "systemctl --user daemon-reload",
      "systemctl --user enable --now mendo-chat.service",
      "systemctl --user enable --now mendo-workbench.service",
      "systemctl --user restart mendo-chat.service",
      "systemctl --user restart mendo-workbench.service",
      "systemctl --user is-active --quiet mendo-chat.service",
      "systemctl --user is-active --quiet mendo-workbench.service",
      "attempt=0; until curl --fail --silent --show-error --max-time 10 http://127.0.0.1:4174/api/health >/dev/null; do attempt=$((attempt + 1)); test \"$attempt\" -lt 30 || exit 1; sleep 1; done",
      var.workbench_trusted_lan_enabled ? "attempt=0; until curl --fail --silent --show-error --max-time 10 http://127.0.0.1:4180/api/workbench/health >/dev/null; do attempt=$((attempt + 1)); test \"$attempt\" -lt 30 || exit 1; sleep 1; done" : "set -a; . '${var.observatory_home}/env/workbench.env'; set +a; attempt=0; until curl --fail --silent --show-error --max-time 10 -H \"X-Mendo-Workbench-Auth: $MENDO_WORKBENCH_PROXY_TOKEN\" http://127.0.0.1:4180/api/workbench/health >/dev/null; do attempt=$((attempt + 1)); test \"$attempt\" -lt 30 || exit 1; sleep 1; done",
    ]
  }

  depends_on = [
    data.external.watershop_host_key,
    azurerm_role_assignment.foundry_runtime,
    local_sensitive_file.workbench_environment,
  ]
}
